name = "tdb-cron"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["30 23 * * *"]

[[kv_namespaces]]
binding = "TDB_LOG"
id = "fb4ad82636b14f90aeeaa891db068ba02"
preview_id = "fb4ad82636b14f90aeeaa891db068ba02"

[observability]
enabled = true
